### PR TITLE
fix 'sticky' bug

### LINKED ISSUE #364: fix 'sticky' bug
may be one problem or may be two problems.
when answering openchain Q you get a fixlicense tool.
click on fixlicense tool when there are no licenses to fix.
click on some blocks (bottom blocks, white space in middle blocks, following quad blocks). Nothing happens (which is correct). Hit space bar to continue. Block that was falling stays stuck in midair. I think may be in 'sticky' (ie fix license would keep working) but couldn't verify.

Do similar with OpenC2 'move block' (except don't click on a valid block). Hit space bar. Might end up sticky.

DItto 'delete block' and fixvuln

### PR DESCRIPTION
**Pull request by WanjikuMac**
closes #364

### CODE REVIEW

File: lib/quadquizaminos_web/live/tetris_live.ex [hunk 1]
```diff
@@ -512,6 +513,7 @@ defmodule QuadquizaminosWeb.TetrisLive do
         %{"x" => x, "y" => y, "color" => color},
         %{assigns: %{moving_block: true}} = socket
       ) do
+    IO.puts("====wanjiku is lovely====")
```
Comment (sigu) [inline lib/quadquizaminos_web/live/tetris_live.ex:516]: Lets do away with the lovely print here

File: lib/quadquizaminos_web/live/tetris_live.ex [hunk 2]
```diff
@@ -619,19 +621,35 @@ defmodule QuadquizaminosWeb.TetrisLive do
...
+    ycoordinate =
+      socket.assigns.bottom
+      |> Map.keys()
+      |> Enum.map(fn value -> elem(value, 1) end)
+      |> Enum.map(fn c -> Integer.to_string(c) end)
+
+    if y in ycoordinate do
+      {x, y} = parse_to_integer(x, y)
+      {x1, y1, color} = block_coordinates
+      powers = socket.assigns.powers -- [:moveblock]
```
Comment (sigu) [inline lib/quadquizaminos_web/live/tetris_live.ex:635]: We should only remove the power once we successfully use it up.

File: lib/quadquizaminos_web/live/tetris_live.ex [hunk 3]
```diff
@@ -619,19 +621,35 @@ defmodule QuadquizaminosWeb.TetrisLive do
...
-      bottom: bottom,
-      powers: powers,
-      adding_block: false,
-      moving_block: false
-    )
+      bottom =
+        socket.assigns.bottom
+        |> Map.delete({x1, y1})
+        |> Map.merge(%{{x, y} => {x, y, color}})
+        |> IO.inspect()
```
Comment (sigu) [inline lib/quadquizaminos_web/live/tetris_live.ex:641]: Remove the inspect

File: lib/quadquizaminos_web/live/tetris_live.ex (hunk 1 above)
Comment (WanjikuMac) [reply lib/quadquizaminos_web/live/tetris_live.ex:516]: smh, forgot to remove this

File: lib/quadquizaminos_web/live/tetris_live.ex [hunk 4]
```diff
@@ -619,19 +621,35 @@ defmodule QuadquizaminosWeb.TetrisLive do
...
+
+      assign(socket,
+        bottom: bottom,
+        powers: powers,
+        adding_block: false,
+        moving_block: false
+      )
+    else
+      powers = socket.assigns.powers -- [:moveblock]
```
Comment (sigu) [inline lib/quadquizaminos_web/live/tetris_live.ex:650]: Since we never successfully used the power up we shold not remove it from the socket

**Review by sigu — CHANGES_REQUESTED** [review]

File: lib/quadquizaminos_web/live/tetris_live.ex (hunk 2 above)
Comment (WanjikuMac) [reply lib/quadquizaminos_web/live/tetris_live.ex:634]: This the bottom point so it will get used

File: lib/quadquizaminos_web/live/tetris_live.ex (hunk 3 above)
Comment (WanjikuMac) [reply lib/quadquizaminos_web/live/tetris_live.ex:640]: noted

File: lib/quadquizaminos_web/live/tetris_live.ex (hunk 4 above)
Comment (WanjikuMac) [reply lib/quadquizaminos_web/live/tetris_live.ex:649]: I agree with this

File: lib/quadquizaminos_web/live/tetris_live.ex [hunk 5]
```diff
@@ -619,19 +620,34 @@ defmodule QuadquizaminosWeb.TetrisLive do
...
+      
+      assign(socket,
+        bottom: bottom,
+        powers: powers,
+        adding_block: false,
+        moving_block: false
+      )
+    else
+      assign(socket, powers: powers, moving_block: false, adding_block: false)
```
Comment (sigu) [inline lib/quadquizaminos_web/live/tetris_live.ex:649]: does that mean If we reset `moving_block` and `adding_block` to `false` we will be able to click on the super power again and use it?

**Review by sigu — APPROVED** [review]

File: lib/quadquizaminos_web/live/tetris_live.ex (hunk 5 above)
Comment (WanjikuMac) [reply lib/quadquizaminos_web/live/tetris_live.ex]: yes, the two events, have a hovering block so setting them to false does away with that but the power-up remains, so when the brick becomes part of the bottom, then a player can use the power-up previously earned at that point
